services:
  database:
    image: ${DOCKER_IMG_NAME}:${DOCKER_IMG_TAG}
    volumes:
      - database_volume:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    ports:
      - ${HOST_PORT}:${DATABASE_PORT}

volumes:
  database_volume:
    name: database_volume
    external: true