services:
  # 데이터베이스 (배포용)
  database:
    image: ${DB_IMG_NAME}:${DB_IMG_TAG}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    volumes:
      - database_volume:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always

volumes:
  database_volume:
    name: database_volume
    driver: local